# config/train/colab_a100.yaml

defaults:
  - baseline
  - _self_

train:
  batch_size:            128
  gradient_accumulation: 1
  epochs:                5
  ramp_steps:            1000

runtime:
  torch_compile:         true
  compile_fullgraph:     true
  bf16:                  true
  tf32:                  true
  dataloader_workers:    6
  pin_memory:            true
  group_by_length:       false
