# colab-env/colab.yaml

env:
  hf_cache: "/content/drive/MyDrive/hf_cache"

data:
  raw_path: "/content/drive/MyDrive/data/ai_detector/raw/modern.jsonl"
  processed_dir: "/content/drive/MyDrive/data/ai_detector/processed/"
